name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-win64:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build win-x64
      run: dotnet publish Portforwarded.Server/Portforwarded.Server.csproj -r win-x64 --self-contained -c Release -o published/win-x64

  build-linux64:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build linux-x64
      run: dotnet publish Portforwarded.Server/Portforwarded.Server.csproj -r linux-x64 --self-contained -c Release -o published/linux-x64
  build-osx64:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build osx-x64
      run: dotnet publish Portforwarded.Server/Portforwarded.Server.csproj -r osx-x64 --self-contained -c Release -o published/osx-x64