name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build win-x64
      run: dotnet build Portforwarded.Server/Portforwarded.Server.csproj --no-restore -r win-x64
    - name: Build win-arm64
      run: dotnet build Portforwarded.Server/Portforwarded.Server.csproj --no-restore -r win-arm64
    - name: Build linux-x64
      run: dotnet build Portforwarded.Server/Portforwarded.Server.csproj --no-restore -r linux-x64
    - name: Build linux-arm64
      run: dotnet build Portforwarded.Server/Portforwarded.Server.csproj --no-restore -r linux-arm64
    - name: Build osx-x64
      run: dotnet build Portforwarded.Server/Portforwarded.Server.csproj --no-restore -r osx-x64
    - name: Build osx.11.0-arm64
      run: dotnet build Portforwarded.Server/Portforwarded.Server.csproj --no-restore -r osx.11.0-arm64